#ifndef __HQSYS_PCBA_
#define __HQSYS_PCBA_

typedef enum
{
	PCBA_INFO_UNKNOW = 0,

	YAMATO_PCBA_EVB_SKU_EVB_1_5 = 1,
	YAMATO_PCBA_EVB_SKU_EVB_2_6,
	YAMATO_PCBA_EVB_SKU_EVT_1_5,
	YAMATO_PCBA_EVB_SKU_EVT_2_6,
	YAMATO_PCBA_EVB_SKU_DVT_1_5,
	YAMATO_PCBA_EVB_SKU_DVT_2_6,
	YAMATO_PCBA_EVB_SKU_PVT_1_5,
	YAMATO_PCBA_EVB_SKU_PVT_2_6,

	YAMATO_PCBA_EVT_SKU_EVB_1_5 = 9,
	YAMATO_PCBA_EVT_SKU_EVB_2_6,
	YAMATO_PCBA_EVT_SKU_EVT_1_5,
	YAMATO_PCBA_EVT_SKU_EVT_2_6,
	YAMATO_PCBA_EVT_SKU_DVT_1_5,
	YAMATO_PCBA_EVT_SKU_DVT_2_6,
	YAMATO_PCBA_EVT_SKU_PVT_1_5,
	YAMATO_PCBA_EVT_SKU_PVT_2_6,
	
	YAMATO_PCBA_DVT1_SKU_EVB_1_5 = 17,
	YAMATO_PCBA_DVT1_SKU_EVB_2_6,
	YAMATO_PCBA_DVT1_SKU_EVT_2_6,
	YAMATO_PCBA_DVT1_SKU_EVT_1_5,
	YAMATO_PCBA_DVT1_SKU_DVT_1_5,
	YAMATO_PCBA_DVT1_SKU_DVT_2_6,
	YAMATO_PCBA_DVT1_SKU_PVT_1_5,
	YAMATO_PCBA_DVT1_SKU_PVT_2_6,
	
	YAMATO_PCBA_DVT2_SKU_EVB_1_5 = 25,
	YAMATO_PCBA_DVT2_SKU_EVB_2_6,
	YAMATO_PCBA_DVT2_SKU_EVT_2_6,
	YAMATO_PCBA_DVT2_SKU_EVT_1_5,
	YAMATO_PCBA_DVT2_SKU_DVT_1_5,
	YAMATO_PCBA_DVT2_SKU_DVT_2_6,
	YAMATO_PCBA_DVT2_SKU_PVT_1_5,
	YAMATO_PCBA_DVT2_SKU_PVT_2_6,

	YAMATO_PCBA_PVT_SKU_EVB_1_5 = 33,
	YAMATO_PCBA_PVT_SKU_EVB_2_6,
	YAMATO_PCBA_PVT_SKU_EVT_1_5,
	YAMATO_PCBA_PVT_SKU_EVT_2_6,
	YAMATO_PCBA_PVT_SKU_DVT_1_5,
	YAMATO_PCBA_PVT_SKU_DVT_2_6,
	YAMATO_PCBA_PVT_SKU_PVT_1_5,
	YAMATO_PCBA_PVT_SKU_PVT_2_6,
	
	YAMATO_PCBA_MP_SKU_EVB_1_5 = 41,
	YAMATO_PCBA_MP_SKU_EVB_2_6,
	YAMATO_PCBA_MP_SKU_EVT_1_5,
	YAMATO_PCBA_MP_SKU_EVT_2_6,
	YAMATO_PCBA_MP_SKU_DVT_1_5,
	YAMATO_PCBA_MP_SKU_DVT_2_6,
	YAMATO_PCBA_MP_SKU_PVT_1_5,
	YAMATO_PCBA_MP_SKU_PVT_2_6,

	PCBA_INFO_END,
} PCBA_INFO;

typedef enum
{
	STAGE_UNKNOW = 0,
	EVB,
	EVT,
	DVT1,
	DVT2,
	PVT,
	MP,
} PROJECT_STAGE;

struct project_stage {
	int voltage_min;
	int voltage_max;
	PROJECT_STAGE project_stage;
};

struct PCBA_MSG {
	PCBA_INFO huaqin_pcba_config;
	PROJECT_STAGE pcba_stage;
	unsigned int pcba_config;
	unsigned int pcba_config_count;
	const char *rsc;
	const char *sku;
};

struct PCBA_MSG* get_pcba_msg(void);

#endif
