#
# Makefile for the GalaxyCore touchscreen driver.
#
obj-$(CONFIG_TOUCHSCREEN_GCORE) += gc7202m.o
gc7202m-y	+=  gcore_drv_main.o
gc7202m-y	+=  gcore_drv_mtk.o
gc7202m-y	+=  gcore_drv_fw_update.o
gc7202m-y	+=  gcore_drv_interface.o
gc7202m-y	+=  gcore_drv_mp_test.o
